---
tags:
  - study
  - 이펙티브자바
title: try-finally 보다는 try-with-resources 를 사용하라
chapter: 아이템 9
---
# try-finally 보다는 try-with-resources 를 사용하라

- 자바에는 close  메서드를 호출해서 직접 닫아야 하는 자원이 많다.
- 클라이언트가 놓치기 쉬워서 성능문제로 이어지기도 한다. 그리고 아이템 8에서 언급했듯이 finalizer 를 사용할 수 있지만 신뢰할 수 없다.
- 전통적으로는 try-finally가 쓰였다.
## try-finally
```java
// 코드 9-1 try finally
static String firstLineOfFile(String path) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(path));
        try {
            return br.readLine();
        } finally {
            br.close();
        }
    }
```

```java
public class Copy {
    private static final int BUFFER_SIZE = 8 * 1024;

    // 코드 9-2 자원이 둘 이상이면 try-finally 방식은 너무 지저분하다! (47쪽)
    static void copy(String src, String dst) throws IOException {
        InputStream in = new FileInputStream(src);
        try {
            OutputStream out = new FileOutputStream(dst);
            try {
                byte[] buf = new byte[BUFFER_SIZE];
                int n;
                while ((n = in.read(buf)) >= 0)
                    out.write(buf, 0, n);
            } finally {
                out.close();
            }
        } finally {
            in.close();
        }
    }
```
- 예시에서 볼 수 있듯이 가독성이 떨어진다.
- 또한 두가지 예외가 모두 발생할 경우 두번째 예외가 첫번째 예외를 덮어버려서 첫번째 예외에 대한 정보가 남지 않게되고 디버깅을 어렵게 한다.

```java
MyResource myResource = null;
try {
    myResource = new MyResource();
    myResource.doSomething(); // 1 예외 발생
} finally {
    if (myResource != null) {
        myResource.close(); // 2 예외 발생
    }
}
```
- 좀더 쉬운 예시로 보면 1번의 예외 발생후 finally 안에서 다시한번 예외가 발생하게 되면 첫번째 예외는 디버깅이 어렵게 된다. 

## try-with-resources

- try-with-resources를 사용하면 앞서 말한 문제들이 해결된다. 이를 사용하기 위해서는 해당 자원이 AutoCloseable 인터페이스를 구현해야 한다. 이미 많은 라이브러리들이 구현되어있다.

```java
// 9-3 try-with-resources

static String firstLineOfFile(String path) throws IOException {
        try (BufferedReader br = new BufferedReader(
                new FileReader(path))) {
            return br.readLine();
        }
```
```java
// 9-4 try-with-resources
static void copy(String src, String dst) throws IOException {
        try (InputStream   in = new FileInputStream(src);
             OutputStream out = new FileOutputStream(dst)) {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while ((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        }
    }
```

- 가독성이 높고 문제를 진단하기도 좋다.
- `try-with-resources`는 가독성이 높고 문제를 진단하기에도 훨씬 좋다. 만약 `br.readLine()`에서 예외가 발생하고 숨겨져있는 `close`에서도 예외가 발생했다면 `close`에서 발생한 예외는 숨겨지고 `readLine`에서 발생한 예외가 기록된다. 또한 뒤에 발생한 에러는 사라지는 것이 아닌 스택 추적 내역에 `suppressed(숨겨졌다)`는 label을 달고 출력된다. `Throwable`의 `getSuppressed`메서드를 사용해서 뒤에 쌓여있는 에러를 가져올 수도 있다.  
```java
// 9-5 try-with-resources
static String firstLineOfFile(String path, String defaultVal) {
        try (BufferedReader br = new BufferedReader(
                new FileReader(path))) {
            return br.readLine();
        } catch (IOException e) {
            return defaultVal;
        }
    }
```
- try-finally 처럼 catch 절을 사용할 수 도 있다.

